Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: meta1
          AttributeType: S
        - AttributeName: meta2
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification:
        Enabled: False
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: False
      GlobalSecondaryIndexes:
        - IndexName: filter
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: email
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: email
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: sk-meta1-index
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: meta1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: meta1-pk-index
          KeySchema:
            - AttributeName: meta1
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: meta1-sk-index
          KeySchema:
            - AttributeName: meta1
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL